"""init

Revision ID: 30aaec7f8a29
Revises: 
Create Date: 2025-06-25 20:56:15.044161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30aaec7f8a29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listed_symbols',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('organ_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listed_symbols', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listed_symbols_symbol'), ['symbol'], unique=True)

    op.create_table('stock_symbols',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_symbols')
    with op.batch_alter_table('listed_symbols', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listed_symbols_symbol'))

    op.drop_table('listed_symbols')
    # ### end Alembic commands ###
